# Generated by Django 4.2.29 on 2026-04-04 19:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='Home Hub', max_length=128)),
                ('latitude', models.FloatField(default=42.6977)),
                ('longitude', models.FloatField(default=23.3219)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IREmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_addr', models.IntegerField()),
                ('name', models.CharField(default='AC Unit', max_length=128)),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emitters', to='api.hub')),
            ],
            options={
                'unique_together': {('hub', 'short_addr')},
            },
        ),
        migrations.CreateModel(
            name='SmartPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_addr', models.IntegerField()),
                ('name', models.CharField(default='Smart Plug', max_length=128)),
                ('online', models.BooleanField(default=False)),
                ('power_on', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugs', to='api.hub')),
            ],
            options={
                'unique_together': {('hub', 'short_addr')},
            },
        ),
        migrations.CreateModel(
            name='SmartPlugEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_on', models.BooleanField(default=True)),
                ('measured_watts', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.smartplug')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('heat', 'Heat'), ('cool', 'Cool')], default='heat', max_length=8)),
                ('comfort_temp_c', models.IntegerField(default=21)),
                ('setback_temp_c', models.IntegerField(default=18)),
                ('sleep_hour', models.IntegerField(default=23)),
                ('sleep_minute', models.IntegerField(default=0)),
                ('wake_hour', models.IntegerField(default=7)),
                ('wake_minute', models.IntegerField(default=0)),
                ('preheat_minutes', models.IntegerField(default=45)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.iremitter')),
            ],
        ),
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('set_schedule', 'Set Schedule'), ('set_ac', 'Set AC State'), ('set_plug', 'Set Plug State')], max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.hub')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ACEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setpoint_c', models.IntegerField(default=21)),
                ('mode', models.CharField(choices=[('heat', 'Heat'), ('cool', 'Cool'), ('fan', 'Fan'), ('auto', 'Auto'), ('off', 'Off')], default='heat', max_length=16)),
                ('power_on', models.BooleanField(default=True)),
                ('outdoor_temp_c', models.FloatField(blank=True, null=True)),
                ('estimated_watts', models.IntegerField(default=0)),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.iremitter')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
    ]
