# Generated by Django 4.2.30 on 2026-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_smartplugevent_energy_voltage_current"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingcommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("set_schedule", "Set Schedule"),
                    ("set_ac", "Set AC State"),
                    ("set_plug", "Set Plug State"),
                    ("scan_network", "Scan Zigbee Network"),
                ],
                max_length=32,
            ),
        ),
    ]
