# Generated by Django 4.2.30 on 2026-04-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_pendingcommand_command_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hub",
            name="last_network_scan",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
